version: 2
sources:
  - name: raw_pay
    database: eco-rune-459817-m9
    schema: raw_pay        # ← nome esatto del dataset in BigQuery
    tables:
      - name: ordini
      - name: transazioni
      - name: piani
      - name: rinnovi
      - name: abbonamenti
      - name: utenti
      - name: coupon
      - name: metodi